# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
use_frameworks!

target 'RawVideo' do
  project 'RawVideo.xcodeproj'
  workspace 'RawVideo.xcworkspace'

  #pod 'AzureCommunicationCalling', '2.8.0'
  pod 'AzureCommunicationCommon'
end
