# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SwiftPushTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AzureCommunicationChat', '~> 1.3.1'

  # Pods for SwiftPushTest

end

target 'SwiftPushTestNotificationExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AzureCommunicationChat', '~> 1.3.1'

  # Pods for SwiftPushTestNotificationExtension

end

