platform :ios, '13.0'
use_frameworks!

ACSFrameworkVersion = '2.7.0-beta.3'

target 'iOSVideo' do
  pod 'AzureCommunicationCalling', ACSFrameworkVersion
end

post_install do |installer|
  app_project = Xcodeproj::Project.open(Dir.glob("*.xcodeproj")[0])
  app_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)']
          config.build_settings['OTHER_SWIFT_FLAGS'] << '-D BETA'
          app_project.save
        end
  end
end
